# Generated by Django 4.2.4 on 2023-12-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='gpx',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_file',
            field=models.FileField(default=b'', upload_to=''),
            preserve_default=False,
        ),
    ]
